server:
    port: 8764
security:
  oauth2:
    client:
      clientId: client1
      client-secret: client1
      access-token-uri: http://auth:auth@localhost:8763/oauth/token
      user-authorization-uri: http://auth:auth@localhost:8763/oauth/authorize
    resource:
      user-info-uri: http://auth:auth@localhost:8763/user/info
      prefer-token-info: false
    sso:
      login-path: /databash/login
      
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_sec_oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
    registry-fetch-interval-seconds: 10